export { analyzeSessions } from "./analyze.js";
export { claudeCodeAdapter, eventFileAdapter, readFromAdapters } from "./adapters.js";
export type { SessionAdapter } from "./adapters.js";
export { buildModelBreakdown, primaryModel } from "./breakdown.js";
export type { ModelBreakdownRow } from "./breakdown.js";
export { recommendationCategory } from "./categorize.js";
export type { RecommendationCategory } from "./categorize.js";
export { paint, shouldColor } from "./color.js";
export type { SingleStyle, Style } from "./color.js";
export { parseClaudeCodeTranscript, readClaudeCodeSessions } from "./claude-code.js";
export { latestDecision, readDecisions, recordDecision } from "./decisions.js";
export type { Decision, DecisionStatus } from "./decisions.js";
export { generateDashboard } from "./dashboard.js";
export { appendEvent, readEvents } from "./io.js";
export { describeJevConnection } from "./jev-connection.js";
export type { JevConnection } from "./jev-connection.js";
export { createControlledOptimizer } from "./optimizer.js";
export { calculateSessionMetrics, modelTier } from "./metrics.js";
export { extractClaudeSemanticItems, judgeRelevance, readClaudeSemanticItems } from "./relevance.js";
export { filterToRecentSessions } from "./recent.js";
export { filterEventsByTime, parsePositiveInt, resolveTimeWindow } from "./time.js";
export type { TimeWindow, TimeWindowOptions } from "./time.js";
export type * from "./types.js";
export type { ControlledOptimizerOptions } from "./optimizer.js";
export { verifyRecommendation } from "./verify.js";
export type { VerificationResult } from "./verify.js";
export { checkForUpdate, compareVersions, fetchLatestVersion, getOwnVersion, isCacheStale } from "./version.js";
export type { CheckForUpdateOptions, UpdateAvailable, UpdateCache } from "./version.js";
